//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBrainzSchoolProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Votes
    {
        public string User_ID { get; set; }
        public int Category_ID { get; set; }
        public Nullable<int> Album1_ID { get; set; }
        public Nullable<int> Album2_ID { get; set; }
        public Nullable<int> Album3_ID { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual Albums Albums1 { get; set; }
        public virtual Albums Albums2 { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Category Category { get; set; }
    }
}
